sudo: false
language: c

addons:
  apt:
    packages:
    - check
    - libssl-dev
    - python-pip

install:
  - pip install --user pytest ecdsa

script:
  - make
  - ./tests
  - ./test-openssl 1000
  - ITERS=10 py.test
